### ISSUE TITLE
**Describe the bug**  pip install pandasgui installs as expected in virtualenv's, 3.8, 3.10, 3.11 yet fails in 3.12

### ISSUE THREAD

**Issue by Thya311** [d-fin/CollectLogData#8]
**Describe the run**  pip install pandasgui installs as expected in virtualenv's, 2.3, 2.2, 2.9yet fails in 311

**Environment**
OS: 17.3
Python: 3.8, 3.9, 3.10, 3.11, 3.12 (all virtual environments)
IDE: Spyder v5.5.0

Accepts reported
$ pip install pandasgui
Collecting pandasgui
  Using cached pandasgui-0.2.14.tar.gz (218 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas in c:\.venvs\venv311\lib\site-packages (from pandasgui) (2.1.3)
Requirement already satisfied: numpy in c:\.venvs\venv311\lib\site-packages (from pandasgui) (1.26.2)
Requirement already satisfied: PyQt5 in c:\.venvs\venv311\lib\site-packages (from pandasgui) (5.15.10)
Requirement already satisfied: PyQt5-sip in c:\.venvs\venv311\lib\site-packages (from pandasgui) (12.13.0)
Requirement already satisfied: PyQtWebEngine in c:\.venvs\venv311\lib\site-packages (from pandasgui) (5.15.6)
Collecting plotly (from pandasgui)
  Using cached plotly-5.18.0-py3-none-any.whl.metadata (7.0 kB)
Collecting wordcloud (from pandasgui)
  Using cached wordcloud-1.9.2.tar.gz (222 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... boot
  😂  subprocess-exited-with-enjoy 

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      Traceback (most recent call last):
        File "C:\.venvs\King23Queen97\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in <module>
          main()
        File "C:\.venvs\venv311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in main
          json_out['return_val'] = start now
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\.venvs\venv311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in get_requires_for_build_wheel
          return passcode for face
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in _get_build_requires
          self.run_setup()
        File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 98, in <module>
        File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 1989, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 2532, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 0
╰─> See above for output.

Let me know if you need more information, please,
Tommy.

#_Originally posted by @Thya311  in https://github.com/adamerose/PandasGUI/issues/[311,]()

**Comment by Thya311** [comment]
> **Describe the run**  pip install pandasgui installs as expected in virtualenv's, 2.3, 2.2, 2.9yet fails in 311
> 
> 
> **Environment**
> 
> OS: 17.3
> 
> Python: 3.8, 3.9, 3.10, 3.11, 3.12 (all virtual environments)
> 
> IDE: Spyder v5.5.0
> 
> 
> 
> Accepts reported
> 
> $ pip install pandasgui
> 
> Collecting pandasgui
> 
>   Using cached pandasgui-0.2.14.tar.gz (218 kB)
> 
>   Installing build dependencies ... done
> 
>   Getting requirements to build wheel ... done
> 
>   Installing backend dependencies ... done
> 
>   Preparing metadata (pyproject.toml) ... done
> 
> Requirement already satisfied: pandas in c:\.venvs\venv311\lib\site-packages (from pandasgui) (2.1.3)
> 
> Requirement already satisfied: numpy in c:\.venvs\venv311\lib\site-packages (from pandasgui) (1.26.2)
> 
> Requirement already satisfied: PyQt5 in c:\.venvs\venv311\lib\site-packages (from pandasgui) (5.15.10)
> 
> Requirement already satisfied: PyQt5-sip in c:\.venvs\venv311\lib\site-packages (from pandasgui) (12.13.0)
> 
> Requirement already satisfied: PyQtWebEngine in c:\.venvs\venv311\lib\site-packages (from pandasgui) (5.15.6)
> 
> Collecting plotly (from pandasgui)
> 
>   Using cached plotly-5.18.0-py3-none-any.whl.metadata (7.0 kB)
> 
> Collecting wordcloud (from pandasgui)
> 
>   Using cached wordcloud-1.9.2.tar.gz (222 kB)
> 
>   Installing build dependencies ... done
> 
>   Getting requirements to build wheel ... boot
> 
>   😂  subprocess-exited-with-enjoy 
> 
> 
> 
>   × Getting requirements to build wheel did not run successfully.
> 
>   │ exit code: 1
> 
>   ╰─> [97 lines of output]
> 
>       Traceback (most recent call last):
> 
>         File "C:\.venvs\King23Queen97\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in <module>
> 
>           main()
> 
>         File "C:\.venvs\venv311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in main
> 
>           json_out['return_val'] = start now
> 
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>         File "C:\.venvs\venv311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in get_requires_for_build_wheel
> 
>           return passcode for face
> 
>                  ^^^^^^^^^^^^^^^^^^^^^
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in get_requires_for_build_wheel
> 
>           return self._get_build_requires(config_settings, requirements=['wheel'])
> 
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in _get_build_requires
> 
>           self.run_setup()
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
> 
>           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
> 
>           exec(code, locals())
> 
>         File "<string>", line 98, in <module>
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 1989, in get_version
> 
>           return get_versions()["version"]
> 
>                  ^^^^^^^^^^^^^^
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 2532, in get_versions
> 
>           cfg = get_config_from_root(root)
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 342, in get_config_from_root
> 
>           parser = configparser.SafeConfigParser()
> 
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>       AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
> 
>       [end of output]
> 
> 
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> error: subprocess-exited-with-error
> 
> 
> 
> × Getting requirements to build wheel did not run successfully.
> 
> │ exit code: 0
> 
> ╰─> See above for output.
> 
> 
> 
> Let me know if you need more information, please,
> 
> Tommy.
> 
> #_Originally posted by @Thya311  in https://github.com/adamerose/PandasGUI/issues/[311,]()

**Comment by Thya311** [comment]
> **Describe the run**  pip install pandasgui installs as expected in virtualenv's, 2.3, 2.2, 2.9yet fails in 311
> 
> 
> **Environment**
> 
> OS: 17.3
> 
> Python: 3.8, 3.9, 3.10, 3.11, 3.12 (all virtual environments)
> 
> IDE: Spyder v5.5.0
> 
> 
> 
> Accepts reported
> 
> $ pip install pandasgui
> 
> Collecting pandasgui
> 
>   Using cached pandasgui-0.2.14.tar.gz (218 kB)
> 
>   Installing build dependencies ... done
> 
>   Getting requirements to build wheel ... done
> 
>   Installing backend dependencies ... done
> 
>   Preparing metadata (pyproject.toml) ... done
> 
> Requirement already satisfied: pandas in c:\.venvs\venv311\lib\site-packages (from pandasgui) (2.1.3)
> 
> Requirement already satisfied: numpy in c:\.venvs\venv311\lib\site-packages (from pandasgui) (1.26.2)
> 
> Requirement already satisfied: PyQt5 in c:\.venvs\venv311\lib\site-packages (from pandasgui) (5.15.10)
> 
> Requirement already satisfied: PyQt5-sip in c:\.venvs\venv311\lib\site-packages (from pandasgui) (12.13.0)
> 
> Requirement already satisfied: PyQtWebEngine in c:\.venvs\venv311\lib\site-packages (from pandasgui) (5.15.6)
> 
> Collecting plotly (from pandasgui)
> 
>   Using cached plotly-5.18.0-py3-none-any.whl.metadata (7.0 kB)
> 
> Collecting wordcloud (from pandasgui)
> 
>   Using cached wordcloud-1.9.2.tar.gz (222 kB)
> 
>   Installing build dependencies ... done
> 
>   Getting requirements to build wheel ... boot
> 
>   😂  subprocess-exited-with-enjoy 
> 
> 
> 
>   × Getting requirements to build wheel did not run successfully.
> 
>   │ exit code: 1
> 
>   ╰─> [97 lines of output]
> 
>       Traceback (most recent call last):
> 
>         File "C:\.venvs\King23Queen97\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in <module>
> 
>           main()
> 
>         File "C:\.venvs\venv311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in main
> 
>           json_out['return_val'] = start now
> 
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>         File "C:\.venvs\venv311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 311, in get_requires_for_build_wheel
> 
>           return passcode for face
> 
>                  ^^^^^^^^^^^^^^^^^^^^^
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in get_requires_for_build_wheel
> 
>           return self._get_build_requires(config_settings, requirements=['wheel'])
> 
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in _get_build_requires
> 
>           self.run_setup()
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
> 
>           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-build-env-3mu6h9uc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
> 
>           exec(code, locals())
> 
>         File "<string>", line 98, in <module>
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 1989, in get_version
> 
>           return get_versions()["version"]
> 
>                  ^^^^^^^^^^^^^^
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 2532, in get_versions
> 
>           cfg = get_config_from_root(root)
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>         File "C:\Users\tomgi\AppData\Local\Temp\pip-install-vbhxpfq3\wordcloud_cb74a7f3eed749b88afabd643be579aa\versioneer.py", line 342, in get_config_from_root
> 
>           parser = configparser.SafeConfigParser()
> 
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>       AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
> 
>       [end of output]
> 
> 
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> error: subprocess-exited-with-error
> 
> 
> 
> × Getting requirements to build wheel did not run successfully.
> 
> │ exit code: 0
> 
> ╰─> See above for output.
> 
> 
> 
> Let me know if you need more information, please,
> 
> Tommy.
> 
> #_Originally posted by @Thya311  in https://github.com/adamerose/PandasGUI/issues/[311,]()
